{
 "title": "Weather Station",
 "description": "Apresenta em tempo real a temperatura, pressão, velocidade e direção do vento, qualidade do ar (PM2.5, PM10, AQI, formaldeído, VOC, CO2), humidade, localização GPS, altitude.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Wind Rose",
   "type": "operato-windrose-panel",
   "description": "Cada pétala aponta para a direção de onde vem o vento,Quanto mais longa for a pétala, mais vezes o vento soprou dessa direção.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\" and r._field == \"Direcao_Graus\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> rename(columns: {_value: \"wind_direction\"})\n  |> keep(columns: [\"_time\", \"wind_direction\"])\n"
    },
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\" and r._field == \"Velocidade_Vento\")\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> rename(columns: {_value: \"wind_speed\"})\n  |> keep(columns: [\"_time\", \"wind_speed\"])\n"
    }
   ]
  },
  {
   "title": "Concentração tVOC(1h)",
   "type": "gauge",
   "description": "Concentração média compostos organicos volateis na ultima hora.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"voc\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Concentração PM2.5(1h)",
   "type": "gauge",
   "description": "Valor médio PM2.5 ultima hora.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"pm25\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Temperatura SF",
   "type": "gauge",
   "description": "Ultimo valor recolhido de temperatura do sensor de formaldehido",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -5m)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Valor médio PM10 ultima hora.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"pm10\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Valor médio PM2.5 ultima hora.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"pm25\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "AQI Index (1h)",
   "type": "gauge",
   "description": "AQI index medio ultima hora",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"aqi\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Concentração PM10(1h)",
   "type": "gauge",
   "description": "Valor médio PM10 ultima hora.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"pm10\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Temperatura BMP280",
   "type": "gauge",
   "description": "Ultimo valor recolhido de temperatura do sensor BMP280",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -10m)  \n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Temp_BMP280\")\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "AQI index medio ultima hora",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"aqi\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Velocidade Vento neste momento.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Velocidade_Vento\" )\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Velocidade Vento neste momento.",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Velocidade_Vento\" )\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Velocidade Vento neste momento.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Direcao_Texto\" )\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Humidade do Ar (1h)",
   "type": "stat",
   "description": "Humidade presente no Ar na ultima hora (média)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> filter(fn: (r) => r._value <= 100)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Temperatura BMP388",
   "type": "gauge",
   "description": "Ultimo valor recolhido de temperatura do sensor BMP388",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -5m)  \n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Temp_BMP388\")\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Concentração média compostos organicos volateis na ultima hora.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"voc\")\n  |> filter(fn: (r) => r._value <= 5000)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Humidade do Solo (1h)",
   "type": "stat",
   "description": "Humidade presente no solo na ultima hora (média)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Humidade_Solo\")\n  |> filter(fn: (r) => r._value <= 100)\n  |> mean()\n"
    }
   ]
  },
  { "title": "Evolução Temporal ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Localização",
   "type": "geomap",
   "description": "Leituras do GPS ultimas 24h",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lon\" or r._field == \"alt\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lon\", \"alt\"])\n"
    },
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"lat\" or r._field == \"lon\" or r._field == \"alt\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"lat\", \"lon\", \"alt\"])\n"
    }
   ]
  },
  {
   "title": "Altitude (24h)",
   "type": "timeseries",
   "description": "Altitude medida pelo GPS ultimas 24h.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"alt\")\n  |> filter(fn: (r) => r._value <= 5000) \n  "
    }
   ]
  },
  {
   "title": "Temperatura BMP388 e BMP280 e SF (24h)",
   "type": "timeseries",
   "description": "Gráfico evolução da temperatura dos sensores BMP388, BMP280 e Sensor de Formaldehyde",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "temp_bmp = from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Temp_BMP388\" or r._field == \"Temp_BMP280\")\n  |> filter(fn: (r) => r._value <= 5000)\n\ntemp_airq = from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> filter(fn: (r) => r._value <= 5000)\n\nunion(tables: [temp_bmp, temp_airq])\n"
    }
   ]
  },
  {
   "title": "Pressão BMP388 e BMP280 (24h)",
   "type": "timeseries",
   "description": "Grafico pressão BMP388 e BMP280 (24h)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "// press_BMP388 e press_BMP280 nas últimas 24h\nfrom(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Press_BMP388\" or r._field == \"Press_BMP280\")\n  |> filter(fn: (r) => r._value <= 5000)\n\n"
    }
   ]
  },
  {
   "title": "Concentração CO2eq (24h)",
   "type": "timeseries",
   "description": "Concentração CO2eq nas ultimas 24h",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"co2eq\")\n  |> filter(fn: (r) => r._value <= 5000)\n\n"
    }
   ]
  },
  { "title": "Concentração Formaldeído (24h)", "type": "library-panel-ref", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 } },
  {
   "title": "Concentração tVOC (24h)",
   "type": "timeseries",
   "description": "Concentração tVOC nas ultimas 24h",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"voc\")\n  |> filter(fn: (r) => r._value <= 5000)\n\n"
    }
   ]
  },
  {
   "title": "Concentração PM10 e PM2.5 (24h)",
   "type": "timeseries",
   "description": "Grafico Concentração PM10 e PM2.5 (24h)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "// press_BMP388 e press_BMP280 nas últimas 24h\nfrom(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"pm10\" or r._field == \"pm25\")\n  |> filter(fn: (r) => r._value <= 5000)\n\n"
    }
   ]
  },
  {
   "title": "AQI Index (24h)",
   "type": "timeseries",
   "description": "AQI Index nas ultimas 24 horas.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"aqi\")\n  |> filter(fn: (r) => r._value <= 100)\n\n"
    }
   ]
  },
  {
   "title": "Humidade Ar (24h)",
   "type": "timeseries",
   "description": "Humidade Ar % nas ultimas 24 horas.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"air_quality_v3\")\n  |> filter(fn: (r) => r._field == \"humidity\")\n  |> filter(fn: (r) => r._value <= 100)\n\n"
    }
   ]
  },
  {
   "title": "Humidade Solo em Volts (24h)",
   "type": "timeseries",
   "description": "Humidade Solo em volts (tensao adc) na ultimas 24 horas.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Tensao_ADC\")\n  |> filter(fn: (r) => r._value <= 5000)\n\n"
    }
   ]
  },
  {
   "title": "Humidade Solo (24h)",
   "type": "timeseries",
   "description": "Humidade Solo em percentagem nas ultimas 24 horas.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"weather_station_v4\")\n  |> filter(fn: (r) => r._field == \"Humidade_Solo\")\n  |> filter(fn: (r) => r._value <= 100)\n\n"
    }
   ]
  }
 ]
}